#Orbo
Partner.create(name: "Orbo Chile", email: "info@orbochile.com", area: "Turismo", liason_name: "Ignacio Espinosa", liason_phone: "56991282228", liason_mail: "comunidad@orbochile.com", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/a15c8439-106d-480e-9e89-e974df2bc5cc/Orbo-Chile-sin-fondo.png?format=1500w", web: "https://www.orbochile.com", fb: "https://www.facebook.com/orbochile", ig: "https://www.instagram.com/orbochile", description: "Plataforma digital que articula la \"industria del buen vivir\" para que la gente se enmore de Chile.", address: "La Capitanía 80", city: "Santiago", state: "Metropolitana", phone: "56920582081")

#Viña El Escorial
Partner.create(name: "Viña El Escorial", email: "reservas@elescorial.cl", area: "Vinos", liason_name: "Rodrigo Espinosa", liason_phone: "56998211333", liason_mail: "respinosa@elescorial.cl", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1590974815048-PY4RTOD2MRSGHFVLXFKS/COML036.png?format=500w", web: "https://www.elescorial.cl/", fb: "https://www.facebook.com/VinaElEscorial/", ig: "https://www.instagram.com/el_escorial_wines/", description: "Viña Boutique con vinos del Valle del Aconcagua y vinos de altura.", address: "Km 1,6 Camino antiguo El Escorial (E-643)", city: "Panquehue", state: "Valparaíso", phone: "56952184041" )

#Viña Villalobos
Partner.create(name: "Villalobos Wines", email: "contacto@villaloboswine.cl", area: "Vinos", liason_name: "Martín Villalobos", liason_phone: "56977793562", liason_mail: "mvillalobosencina@gmail.com", logo_url: "https://images.squarespace-cdn.com/content/5e6fcd04db6a650dd89c8c20/1590974368528-D6KPHH8SBJ0XZYLBPL7N/COML025-min.png?format=300w&content-type=image%2Fpng", web: "https://villaloboswine.cl/en/home/", fb: "https://www.facebook.com/villaloboswine/", ig: "https://www.instagram.com/villaloboswine/", description: "Viña con filosofía de absoluto respecto al entorno donde produce sus vinos.", address: "", city: "Lolol", state: "O'Higgins", phone: "56977793562" )

#Viña Attilio & Mochi
Partner.create(name: "Viña Attilio & Mochi", email: "info@attiliomochi.com", area: "Vinos", liason_name: "Ángela Mochi", liason_phone: "56973882671", liason_mail: "angela@attiliomochi.com", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1598382684861-CQI96FQ7ZZAZUYP2I8RC/COML082-min.png?format=500w", web: "https://www.attiliomochi.com/", fb: "https://www.facebook.com/AttilioMochiWines", ig: "https://www.instagram.com/attiliomochiwines/", description: "Viñateros brasileños creando excepcionales vinos en Casablanca", address: "Ruta F90", city: "Casablanca", state: "Valparaíso", phone: "56973882671" )

#Viña Ventisquero
Partner.create(name: "Viña Ventisquero", email: "hola@ventisquero.com", area: "Vinos", liason_name: "Constanza Alarcón", liason_phone: "56973168565", liason_mail: "calarcon@vwe.cl", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1598459750051-KZG0J53ECTVPRDSMDVZI/image-asset.png?format=500w", web: "https://www.ventisquero.com/", fb: "https://www.facebook.com/VentisqueroWines", ig: "https://www.instagram.com/vventisquero/", description: "Nuestros vinos nacen de la pasión, de la curiosidad, de la libertad creativa, de la aceptación del riesgo, la innovación y una intensa exploración de los sentidos.", address: "Sector La Isla S/N", city: "Doñihue", state: "O'Higgins", phone: "56722444300" )

#Viña Casas del Bosque
Partner.create(name: "Viña Casas del Bosque", email: "wines@casasdelbosque.cl", area: "Vinos", liason_name: "Juan Pablo Edwards", liason_phone: "56984182210", liason_mail: "jedwards@casasdelbosque.cl", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1598578967288-W7NO349A75L0I3TJQ7QT/image-asset.png?format=500w", web: "https://casasdelbosque.cl/", fb: "https://www.facebook.com/vinacasasdelbosque", ig: "https://www.instagram.com/casasdelbosque/", description: "Destacada Viña pionera en el valle de Casablanca, reconocida internacionalmente.", address: "Hijuelas Nº 2 Centro Ex Fundo Santa Rosa", city: "Casablanca", state: "Valparaíso", phone: "56979677320" )

#Viña Narbona Wines
Partner.create(name: "Narbona Wines", email: "contacto@narbonawines.com", area: "Vinos", liason_name: "Pedro Narbona", liason_phone: "56968464852", liason_mail: "narbonawines@gmail.com", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1598649873825-D6CL5FXK6KDMRDE8VSOO/image-asset.png?format=500w", web: "https://narbonawines.com/", fb: "https://www.facebook.com/narbonawines-270368090361991", ig: "https://www.instagram.com/narbonawines/", description: "La filosofía de su dueño es producir el mejor vino de forma natural y respetando el medio ambiente. El cuidado del ecosistema , el uso de energías renovables no convencionales, el manejo de la uva y su posterior proceso, producen vinos con identidad, que pretenden reflejar e interpretar lo que los distintos terroir nos regalan.", address: "Quebrada del Ají", city: "Quillota", state: "Valparaíso", phone: "56968464852" )

#Viña Errázurriz
Partner.create(name: "Viña Errázurriz", email: "contacto@errazuriz.cl", area: "Vinos", liason_name: "María Jesus Astrain", liason_phone: "56988286727", liason_mail: "mjesus.astrain@vfch.cl", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1598648278157-7TPTCWDBUJ3TB3EEWF6I/image-asset.png?format=500w", web: "https://errazuriz.com/", fb: "https://www.facebook.com/errazurizwines/", ig: "https://www.instagram.com/errazurizwines/", description: "Don Maximiano Errázuriz fundó la Viña Errazuriz en 1870 con gran visión de futuro, espíritu innovador y pionero, plantó las primeras parras de vides francesas en el Valle de Aconcagua. Su empuje y creatividad se traspasaron a las futuras generaciones y, en poco más de un siglo, sus descendientes consolidaron la bodega y posicionaron sus vinos entre los más renombrados del mundo. Le invitamos a conocer aquí algunos de los principales hitos que han marcado la historia de esta viña familiar, actualmente uno de los principales referentes del exitoso sector vitivinícola de Chile.", address: "E-639 N°18", city: "Panquehue", state: "Valparaíso", phone: "56968464852" )

#Restaurant Vinolia
Partner.create(name: "Restaurant Vinolia", email: "contacto@vinolia.cl", area: "Gastronomía", liason_name: "", liason_phone: "", liason_mail: "", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1598646523243-FHCDIF5I56BT20EX5CF4/image-asset.png?format=500w", web: "https://www.vinolia.cl/", fb: "https://www.facebook.com/VINOLIA.CHILE/", ig: "https://www.instagram.com/vinolia_chile/", description: "Te invitamos a disfrutar de lo mejor del vino chileno sin salir de Santiago! Sala de cine con cata de vinos, de lunes a sábado, ven y disfruta de nuestra sala de aromas, restaurant y wine bar con after office.", address: "Alonso de Monroy 2869, Vitacura", city: "Santiago", state: "Metropolitana", phone: "56957544897" )

#Viña Haras de Pirque
Partner.create(name: "Viña Haras de Pirque", email: "turismo@haraswines.com", area: "Vinos", liason_name: "Anais Reciné", liason_phone: "56932436886", liason_mail: "turismo@haraswines.com", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1604361087645-Y2J7IE463K8QZMUJGYTD/COML091-min.png?format=500w", web: "https://haraswines.com/", fb: "https://www.facebook.com/harasdepirque", ig: "https://www.instagram.com/vinaharasdepirque/", description: "Haras de Pirque busca crear vinos de excelencia y únicos realizados con la máxima dedicación. Vinos que realmente reflejen la expresión del terroir que provienen en cada botella.", address: "Fundo La Rochuela – Camino Macul S/N, Pirque", city: "Santiago", state: "Metropolitana", phone: "56932436886" )

#TTOO Trip2Chile
Partner.create(name: "Trip2Chile", email: "contacto.trip2chile@gmail.com", area: "Turismo", liason_name: "Diego Poblete", liason_phone: "56936779284", liason_mail: "contacto.trip2chile@gmail.com", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1609888698478-FMO3PXEAOYX5OEC6423W/COML100-min.png?format=500w", web: "https://trip2chile.com/", fb: "", ig: "https://www.instagram.com/trip2chile/", description: "Somos Agencia de viajes /Tour Operador de escapadas unicas, experiencias outdoor, turismo aventura y actividades para parejas, familias y amigos.", address: "", city: "Santiago", state: "Metropolitana", phone: "56936779284" )

#Viña Santa Cruz
Partner.create(name: "Viña Santa Cruz", email: "turismo@vinasantacruz.cl", area: "Vinos", liason_name: "Martín García", liason_phone: "56981560299", liason_mail: "martin@vinasantacruz.cl", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1610547637496-POSJWTB6NQAONLCCIMX3/image-asset.png?format=500w", web: "https://vinasantacruz.cl/", fb: "https://www.facebook.com/vinasantacruzlolol", ig: "https://www.instagram.com/vinasantacruz/", description: "Viñedo Enoturistico de Lolol, Colchagua. Vinos de alta gama, Museos, Teleferico y Restaurant. Somos vino, cultura y entretención. Ven en Familia!", address: "Fundo El Peral", city: "Lolol", state: "O'Higgins", phone: "56972188755" )

#Restaurante Arrecife Secreto
Partner.create(name: "Arrecife Secreto", email: "", area: "Gastronomía", liason_name: "Francisca Echagüe", liason_phone: "", liason_mail: "fran.echague@gmail.com", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1610987271059-5NR91AWB2351DQUQP2EF/COML102-min.png?format=500w", web: "", fb: "", ig: "https://www.instagram.com/arrecifesecreto/", description: "Restaurante en la playa, Sunset music y más!!", address: "", city: "Pichilemu", state: "O'Higgins", phone: "56957686766" )

#Arte Terapia Sofía Martínez
Partner.create(name: "Arte Terapia Sofía Martínez", email: "sofi_martineez@hotmail.com", area: "Arte", liason_name: "Sofía Martínez", liason_phone: "56981360323", liason_mail: "sofi_martineez@hotmail.com", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1611699373000-CUEN5IRV7QFWCKO0FPNB/image-asset.png?format=500w", web: "", fb: "", ig: "https://www.instagram.com/sofiamartinez_art/", description: "", address: "", city: "Santiago", state: "Metropolitana", phone: "56981360323" )

#Galería Tarquinia
Partner.create(name: "Tarquinia Art", email: "contacto@tarquinia.cl", area: "Arte", liason_name: "Christian Jander", liason_phone: "56987695434", liason_mail: "contacto@tarquinia.cl", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1611697158016-UBUW8R0Z31BNP9XZWQ8L/image-asset.png?format=500w", web: "https://tarquinia.cl/", fb: "https://www.facebook.com/Galer%C3%ADa-Tarquinia-100774782070721", ig: "https://www.instagram.com/tarquinia_art/", description: "Nuestro propósito es ser una vitrina cultural de la región, entregando a nuestra comunidad, un espacio para compartir, apreciar, aprender y encantarse del arte. esta pasión se materializó en la creación de un gran equipo que vibra en torno al arte, tanto en la galería como en la academia y muy prontamente en nuestra galería de NFT, sumando la tecnología a nuestras plataformas.", address: "Reñaca Norte 25, Local 5", city: "Viña del Mar", state: "Valparaíso", phone: "56981360323" )

#TTOO W2D
Partner.create(name: "WhatToDo Chile", email: "info@whattodochile.cl", area: "Turismo", liason_name: "Cristóbal Mellado", liason_phone: "56952369786", liason_mail: "info@whattodochile.cl", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1612229192519-D307E9OG23ZZR49H8X9I/COML107-min.png?format=500w", web: "", fb: "", ig: "https://www.instagram.com/wtdchile/", description: "La mejor forma de conocer Chile. Esquí, vinos, cultura, outdoors, paseos en helicópteros, guías profesionales y transporte privado.", address: "", city: "Santiago", state: "Metropolitana", phone: "" )

#PMK Studio
Partner.create(name: "PMK Studio", email: "paulamakarena.a@gmail.com", area: "Arte", liason_name: "Paula Aravena", liason_phone: "56998292792", liason_mail: "paulamakarena.a@gmail.com", logo_url: "https://images.squarespace-cdn.com/content/v1/5e6fcd04db6a650dd89c8c20/1612906311030-EWJUOWNB0RLKIEFXO817/COML104-min.png?format=500w", web: "", fb: "https://www.facebook.com/paulamakarenastudio", ig: "https://www.instagram.com/pmkstudio/", description: "Artista - Arquitecta -Educadora", address: "", city: "Santiago", state: "Metropolitana", phone: "56998292792" )
